"""
src/graphql_queries.py

GraphQL query string constants for the Sui blockchain, extracted verbatim from:
  @evefrontier/dapp-kit/graphql/queries.ts  (v0.0.18)

Generated by: extract_graphql_queries.py
Do NOT hand-edit the GQL strings — update the source DApp Kit package and re-run
the generator script instead.

Owner chain (confirmed by live testnet queries):
  Wallet (0xff09...) → owns PlayerProfile
  PlayerProfile.character_id → Character Sui object ID (0xb789...)
  Character Sui object → owns OwnerCap<Assembly> per assembly it controls
  Character Sui object → owns OwnerCap<Character> (self-authorizing cap)
  OwnerCap<Assembly>.authorized_object_id → Assembly Sui object ID

The power query (GET_OBJECT_DYNAMICFIELD_CHARACTER_WITH_JSON) uses:
  characterOwnerType = {pkg}::access::OwnerCap<{pkg}::character::Character>
  NOT PlayerProfile — it follows the OwnerCap<Character> from the Character Sui object.

FuelConfig/EnergyConfig notes:
  These singletons store data in child Table objects, not directly on the object.
  Use GET_SINGLETON_CONFIG_OBJECT_BY_TYPE with the correct table_name:
    EnergyConfig  → table_name = "assembly_energy"
    FuelConfig    → table_name = "fuel_efficiency"
  Direct object() queries return null for these child tables.

Response path for config singletons (mirrors config.ts parseConfig()):
  result["data"]["objects"]["nodes"][0]["asMoveObject"]["contents"]
        ["extract"]["extract"]["asAddress"]["addressAt"]["dynamicFields"]["nodes"]
  Each node: {"key": {"json": type_id_str}, "value": {"json": value_str}}
"""

# ---------------------------------------------------------------------------
# Tenant Configuration
# (from @evefrontier/dapp-kit/utils/constants.ts TENANT_CONFIG v0.0.18)
# ---------------------------------------------------------------------------

import os

GRAPHQL_ENDPOINT = "https://graphql.testnet.sui.io/graphql"

TENANT_CONFIG: dict[str, dict] = {
    "stillness": {
        "package_id":   "0x28b497559d65ab320d9da4613bf2498d5946b2c0ae3597ccfda3072ce127448c",
        "datahub_host": "world-api-stillness.live.tech.evefrontier.com",
    },
    "utopia": {
        "package_id":   "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75",
        "datahub_host": "world-api-utopia.uat.pub.evefrontier.com",
    },
    "nebula": {
        "package_id":   "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1",
        "datahub_host": "world-api-nebula.test.evefrontier.tech",
    },
}

DEFAULT_TENANT = os.getenv("DEPLOYMENT_ENV", "utopia")

# Table names for config singleton queries
# (from config.ts getEnergyConfig() / getFuelEfficiencyConfig())
ENERGY_CONFIG_TABLE   = "assembly_energy"
FUEL_CONFIG_TABLE     = "fuel_efficiency"


# ---------------------------------------------------------------------------
# Type String Builders
# (mirror @evefrontier/dapp-kit/utils/constants.ts helper functions)
# ---------------------------------------------------------------------------

def character_player_profile_type(pkg: str) -> str:
    """Type filter for the PlayerProfile object owned by a wallet.
    Used in GET_WALLET_CHARACTERS and GET_CHARACTER_AND_OWNED_OBJECTS.
    Variable name: characterPlayerProfileType
    """
    return f"{pkg}::character::PlayerProfile"


def character_owner_cap_type(pkg: str) -> str:
    """Type filter for OwnerCap<Character> — used in the POWER QUERY.
    Variable name: characterOwnerType

    In GET_OBJECT_DYNAMICFIELD_CHARACTER_WITH_JSON, this filters the objects
    owned by the Character Sui object to find its self-authorizing OwnerCap,
    whose authorized_object_id points back to the Character JSON.

    NOT PlayerProfile. The owner chain here goes:
      assembly.owner_cap_id -> OwnerCap_assembly -> owner (Character Sui ID)
      -> Character's owned objects of type OwnerCap<Character>
      -> OwnerCap<Character>.authorized_object_id -> Character object JSON
    """
    return f"{pkg}::access::OwnerCap<{pkg}::character::Character>"


def energy_config_type(pkg: str) -> str:
    """Full Move type string for the EnergyConfig singleton.
    Use with GET_SINGLETON_CONFIG_OBJECT_BY_TYPE and table_name=ENERGY_CONFIG_TABLE.
    """
    return f"{pkg}::energy::EnergyConfig"


def fuel_config_type(pkg: str) -> str:
    """Full Move type string for the FuelConfig singleton.
    Use with GET_SINGLETON_CONFIG_OBJECT_BY_TYPE and table_name=FUEL_CONFIG_TABLE.
    """
    return f"{pkg}::fuel::FuelConfig"


def smart_storage_unit_type(pkg: str) -> str:
    """Full Move type string for SmartStorageUnit.
    Use with GET_OBJECTS_BY_TYPE or GET_OWNED_OBJECTS_BY_TYPE.
    """
    return f"{pkg}::storage_unit::StorageUnit"

# ---------------------------------------------------------------------------
# GraphQL Query String Constants
# (verbatim from @evefrontier/dapp-kit/graphql/queries.ts)
# ---------------------------------------------------------------------------

# --- Core object queries ---

GET_OBJECT_BY_ADDRESS = '''
query GetObjectByAddress($address: SuiAddress!) {
    object(address: $address) {
      address
      version
      digest
      asMoveObject {
        contents {
          type {
            repr
          }
          bcs
        }
      }
    }
  }
'''

GET_OBJECT_WITH_JSON = '''
query GetObjectWithJson($address: SuiAddress!) {
    object(address: $address) {
      address
      version
      digest
      asMoveObject {
        contents {
          type {
            repr
          }
          json
          bcs
        }
      }
    }
  }
'''

GET_OBJECT_WITH_DYNAMIC_FIELDS = '''
query GetObjectWithDynamicFields($objectId: SuiAddress!) {
    object(address: $objectId) {
      asMoveObject {
        contents {
          json
        }
        dynamicFields {
          nodes {
            contents {
              json
              type {
                layout
              }
            }
            name {
              json
              type {
                repr
              }
            }
          }
        }
      }
    }
  }
'''

GET_OBJECT_DYNAMICFIELD_CHARACTER_WITH_JSON = '''
query GetObjectOwnerCharacterOwnerAndInventory(
  $objectId: SuiAddress!
  $characterOwnerType: String!
) {
  object(address: $objectId) {
    asMoveObject {
      contents {
        json
        type { repr }
        bcs
        extract(path: "owner_cap_id") {
          asAddress {
            asObject {
              asMoveObject {
                owner {
                  ... on AddressOwner {
                    address {
                      objects(filter: { type: $characterOwnerType }, last: 1) {
                        nodes {
                          contents {
                            authorizedObj: extract(path: "authorized_object_id") {
                              asAddress {
                                asObject {
                                  asMoveObject {
                                    contents { bcs json }
                                    
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
       energySource: extract(path: "energy_source_id") {
          asAddress {
            asObject {
              asMoveObject {
                contents { bcs json }
              }
            }
          }
        }
        destinationGate: extract(path: "linked_gate_id") {
          asAddress {
            asObject {
              asMoveObject {
                contents { bcs json }
              }
            }
          }
        }
      }
      dynamicFields {
          nodes {
            contents {
              json
              extract(path: "id") {
              asAddress {
                asObject {
                    asMoveObject {
                    contents { bcs json }
                    }
                }
                }      
              }
            }
            name {
              json
              type {
                repr
              }
            }
          }
        }
    }
  }
}
'''

# --- Owner and ownership queries ---

GET_OBJECT_OWNER_AND_OWNED_OBJECTS_BY_TYPE = '''
query GetObjectOwnerAndOwnedObjectByType($object: SuiAddress!, $owned_object_type: String) {
    object(address: $object) {
      owner {
        ... on AddressOwner {
          address {
            address
            objects(
              filter: {
                type: $owned_object_type
              }
            ) {
              nodes {
                contents {
                  bcs
                }
                previousTransaction {
                  effects {
                    timestamp
                  }
                }
              }
            }
          }
        }
      }
    }
  }
'''

GET_OBJECT_OWNER_AND_OWNED_OBJECTS_WITH_JSON = '''
query GetObjectOwnerAndOwnedObjectWithJson($object: SuiAddress!, $owned_object_type: String) {
    object(address: $object) {
      owner {
        ... on AddressOwner {
          address {
            address
            objects(
              filter: {
                type: $owned_object_type
              }
            ) {
              nodes {
                address
                contents {
                  json
                  bcs
                }
                previousTransaction {
                  effects {
                    timestamp
                  }
                }
              }
            }
          }
        }
      }
    }
  }
'''

GET_OWNED_OBJECTS_BY_TYPE = '''
query GetOwnedObjectsByType($owner: SuiAddress!, $object_type: String) {
    address(address: $owner) {
      objects(
        filter: {
          type: $object_type
        }
      ) {
        nodes {
          address
        }
      }
    }
  }
'''

GET_OWNED_OBJECTS_BY_PACKAGE = '''
query GetOwnedObjectsByPackage($owner: SuiAddress!, $packageId: SuiAddress!) {
    objects(
      filter: {
        owner: $owner
        type: { package: $packageId }
      }
    ) {
      nodes {
        address
        version
        asMoveObject {
          contents {
            json
          }
          dynamicFields {
            nodes {
              contents {
                json
                type {
                  layout
                }
              }
              name {
                json
                type {
                  repr
                }
              }
            }
          }
        }
      }
    }
  }
'''

# --- Character queries ---

GET_WALLET_CHARACTERS = '''
query GetWalletCharacters($owner: SuiAddress!, $characterPlayerProfileType: String!) {
    address(
        address: $owner
    ) {
        objects(
            last: 1
            filter: {
                type: $characterPlayerProfileType
            }
        ) {
            nodes {
                contents {
                    extract(path: "character_id") {
                        asAddress {
                            asObject {
                                asMoveObject {
                                    contents {
                                        type {
                                            repr
                                        }
                                        json
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
'''

# --- Singleton and type queries ---

GET_SINGLETON_OBJECT_BY_TYPE = '''
query GetSingletonObjectByType($object_type: String) {
    objects(
      filter: {
        type: $object_type
      }
      first: 1
    ) {
      nodes {
        address
      }
    }
  }
'''

GET_SINGLETON_CONFIG_OBJECT_BY_TYPE = '''
query GetSingletonConfigObjectByType($object_type: String!, $table_name: String!) {
    objects(filter: { type: $object_type }, first: 1) {
        nodes {
            address
            asMoveObject {
                contents {
                    extract(path: $table_name) {
                        extract(path: "id") {
                            asAddress {
                                addressAt {
                                    dynamicFields {
                                        pageInfo {
                                            hasNextPage
                                            endCursor
                                        }
                                        nodes {
                                            key: name {
                                                json
                                            }
                                            value: value {
                                                ... on MoveValue {
                                                    json
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
'''

GET_OBJECTS_BY_TYPE = '''
query GetObjectsByType($object_type: String, $first: Int, $after: String) {
    objects(
      filter: {
        type: $object_type
      }
      first: $first
      after: $after
    ) {
      nodes {
        address
        version
        asMoveObject {
          contents {
            json
            type {
              repr
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
'''

